// Canonical slug → category name mapping, sourced from gol-wp.xml nicenames.
// Use these slugs everywhere to preserve SEO from the original WordPress URLs.

export const CATEGORY_SLUGS: Record<string, string> = {
  'accounts-of-revival':       'Accounts of Revival',
  'amillennialsm':             'Amillennialsm',
  'apologetics':               'Apologetics',
  'arminianism':               'Arminianism',
  'assurance':                 'Assurance',
  'attributes-of-god':         'Attributes of God',
  'augustine-pelagius':        'Augustine & Pelagius',
  'bible-study':               'Bible Study',
  'biographies':               'Biographies',
  'charismatic-movement':      'Charismatic Movement',
  'christian-life':            'Christian Life',
  'christian-modesty':         'Christian Modesty',
  'christian-parenting':       'Christian Parenting',
  'christology':               'Christology',
  'church-discipline':         'Church Discipline',
  'church-history':            'Church History',
  'church-ministry':           'Church Ministry',
  'covenant-theology':         'Covenant Theology',
  'creeds-confessions':        'Creeds & Confessions',
  'decrees-of-god':            'Decrees of God',
  'devotional-life':           'Devotional Life',
  'discernment':               'Discernment',
  'dispensationalism':         'Dispensationalism',
  'doctrine-theology':         'Doctrine & Theology',
  'doctrine-of-god':           'Doctrine of God',
  'doctrine-of-man':           'Doctrine of Man',
  'eschatology':               'Eschatology',
  'eternal-punishment':        'Eternal Punishment',
  'evangelism':                'Evangelism',
  'false-teachers':            'False Teachers',
  'family-worship':            'Family Worship',
  'five-points-of-calvinism':  'Five Points of Calvinism',
  'foreknowledge-of-god':      'Foreknowledge of God',
  'free-will':                 'Free Will',
  'god-the-creator':           'God the Creator',
  'hermeneutics':              'Hermeneutics',
  'holiness-of-god':           'Holiness of God',
  'inspiration-of-scripture':  'Inspiration of Scripture',
  'irresistible-grace':        'Irresistible Grace',
  'justification':             'Justification',
  'leaders-elders':            'Leaders & Elders',
  'limited-atonement':         'Limited Atonement',
  'lords-supper':              "Lord's Supper",
  'love-charity':              'Love & Charity',
  'love-of-god':               'Love of God',
  'marriage':                  'Marriage',
  'partial-preterism':         'Partial Preterism',
  'pastoral-ministry':         'Pastoral Ministry',
  'personal-holiness':         'Personal Holiness',
  'perseverence-of-saints':    'Perseverance of Saints',
  'postmillennialism':         'Postmillennialism',
  'prayer-fasting':            'Prayer & Fasting',
  'preaching':                 'Preaching',
  'predestination-election':   'Predestination & Election',
  'premillennialism':          'Premillennialism',
  'prevenient-grace':          'Prevenient Grace',
  'providence-of-god':         'Providence of God',
  'puritans':                  'Puritans & Puritanism',
  'reformed-theology':         'Reformed Theology',
  'regeneration':              'Regeneration',
  'repentance':                'Repentance',
  'reprobation':               'Reprobation',
  'resurrection':              'Resurrection',
  'revelation-20':             'Revelation 20',
  'revival':                   'Revival',
  'role-of-women':             'Role of Women',
  'salvation':                 'Salvation',
  'sanctification':            'Sanctification',
  'sermons-tracts':            'Sermons & Tracts',
  'sin-temptation':            'Sin & Temptation',
  'sovereignty-of-god':        'Sovereignty of God',
  'the-2nd-coming':            'The 2nd Coming',
  'the-atonement':             'The Atonement',
  'baptists':                  'The Baptists',
  'the-church':                'The Church',
  'credobaptism-paedobaptism': 'Credobaptism & Paedobaptism',
  'unconditional-election':    'Unconditional Election',
  'the-holy-spirit':           'The Holy Spirit',
  'the-law-of-god':            'The Law of God',
  'the-sabbath':               'The Sabbath',
  'the-trinity':               'The Trinity',
  'the-word-of-god':           'The Word of God',
  'total-depravity':           'Total Depravity',
  'worship':                   'Worship',
}

// Reverse map: category name → slug
export const CATEGORY_NAME_TO_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(CATEGORY_SLUGS).map(([slug, name]) => [name, slug])
)

export function categorySlug(name: string): string {
  return CATEGORY_NAME_TO_SLUG[name] ?? name.toLowerCase().replace(/[^\w\s-]/g, '').replace(/[\s_]+/g, '-').replace(/^-+|-+$/g, '')
}

// Parent slug → ordered child slugs, sourced from gol-wp.xml parent/child relationships
export const CATEGORY_CHILDREN: Record<string, string[]> = {
  'reformed-theology':      ['five-points-of-calvinism', 'arminianism', 'covenant-theology', 'free-will', 'decrees-of-god', 'foreknowledge-of-god', 'augustine-pelagius', 'regeneration', 'reprobation'],
  'five-points-of-calvinism': ['total-depravity', 'predestination-election', 'limited-atonement', 'irresistible-grace', 'unconditional-election', 'perseverence-of-saints'],
  'arminianism':            ['prevenient-grace'],
  'doctrine-theology':      ['doctrine-of-god', 'sovereignty-of-god', 'providence-of-god', 'christology', 'the-atonement', 'resurrection', 'doctrine-of-man', 'justification', 'the-holy-spirit', 'the-trinity', 'the-sabbath', 'the-law-of-god', 'the-word-of-god', 'apologetics'],
  'doctrine-of-god':        ['attributes-of-god', 'holiness-of-god', 'love-of-god', 'god-the-creator'],
  'the-word-of-god':        ['inspiration-of-scripture', 'hermeneutics'],
  'salvation':              ['justification', 'evangelism', 'sanctification', 'repentance', 'assurance'],
  'christian-life':         ['personal-holiness', 'devotional-life', 'prayer-fasting', 'love-charity', 'sin-temptation', 'discernment', 'christian-modesty', 'bible-study'],
  'church-ministry':        ['preaching', 'worship', 'revival', 'pastoral-ministry', 'leaders-elders', 'lords-supper', 'church-discipline', 'the-church', 'role-of-women', 'charismatic-movement', 'credobaptism-paedobaptism'],
  'church-history':         ['puritans', 'accounts-of-revival', 'creeds-confessions', 'baptists', 'sermons-tracts', 'false-teachers'],
  'eschatology':            ['dispensationalism', 'premillennialism', 'amillennialsm', 'postmillennialism', 'revelation-20', 'eternal-punishment', 'partial-preterism', 'the-2nd-coming'],
  'home-family':            ['family-worship', 'marriage', 'christian-parenting'],
}
