#!/usr/bin/env python3
"""Expand author bios: short bio in `bio`, full multi-paragraph in `bio_long`."""

import psycopg2

DB = {
    'host': 'db.xhhvbxjllictpxtebeur.supabase.co',
    'dbname': 'postgres',
    'user': 'postgres',
    'password': 'hzwij3$9Tzy%Oq7Y',
    'port': 5432,
}

BIOS_SHORT = {
'john-fox': "John Foxe (1516–1587) was an English historian and Protestant martyrologist, author of Acts and Monuments — Foxe's Book of Martyrs — the most widely read book in Elizabethan England after the Bible.",
'loraine-boettner': "Loraine Boettner (1901–1990) was an American Reformed theologian best known for The Reformed Doctrine of Predestination, one of the most comprehensive popular defenses of Calvinist soteriology ever written in English.",
'arthur-w-pink': "Arthur W. Pink (1886–1952) was a self-taught English Reformed writer whose vast body of devotional and theological works — largely unknown in his lifetime — found a wide readership through Banner of Truth reprints after his death.",
'jonathan-edwards': "Jonathan Edwards (1703–1758) is widely regarded as the greatest theologian and philosopher America has produced, whose preaching, philosophical theology, and account of the Great Awakening shaped evangelical thought across two centuries.",
'benjamin-b-warfield': "Benjamin B. Warfield (1851–1921) was the last and most formidable of the Princeton theologians, whose rigorous defense of biblical inerrancy set the terms for conservative Reformed discussion of Scripture throughout the twentieth century.",
'john-owen': "John Owen (1616–1683) is the greatest English Puritan theologian, whose works on the mortification of sin, communion with God, and the death of Christ remain unsurpassed in the Reformed tradition.",
'john-calvin': "John Calvin (1509–1564) was the foremost second-generation Reformer, whose Institutes of the Christian Religion and decades of ministry in Geneva gave the Reformed tradition its characteristic theological shape.",
'charles-h-spurgeon': "Charles H. Spurgeon (1834–1892) was the most celebrated preacher of the Victorian era — a thoroughgoing Calvinist whose sixty-three volumes of sermons and dozens of books have made him one of the most widely read Protestant authors in history.",
'j-gresham-machen': "J. Gresham Machen (1881–1937) was the most intellectually formidable defender of confessional Presbyterianism in the twentieth century, whose Christianity and Liberalism argued that theological liberalism was not a form of Christianity at all.",
'john-murray': "John Murray (1898–1975) was a Scottish-born Westminster Seminary theologian whose commentary on Romans and Redemption Accomplished and Applied are recognized as masterpieces of careful, rigorous Reformed exegesis and theology.",
'charles-hodge': "Charles Hodge (1797–1878) was the dominant figure in American Reformed theology for over half a century, whose three-volume Systematic Theology and fifty-eight years of teaching at Princeton Seminary shaped American Presbyterianism more than any other individual.",
'archibald-alexander': "Archibald Alexander (1772–1851) was the founding father of Princeton Theological Seminary, whose combination of evangelical warmth and Calvinist doctrinal precision established the character of the Princeton theology for generations.",
'r-l-dabney': "Robert Lewis Dabney (1820–1898) was the most rigorous systematic theologian the Southern Presbyterian tradition produced, whose Systematic Theology and Discussions remain standard works of Reformed scholarship.",
'j-c-ryle': "J. C. Ryle (1816–1900) was the first Bishop of Liverpool and one of the most effective communicators of Reformed evangelical truth in the Victorian church, whose Holiness, Old Paths, and Expository Thoughts on the Gospels have remained continuously in print.",
'john-flavel': "John Flavel (c. 1628–1691) was an English Puritan minister whose devotional writings — especially The Mystery of Providence and Keeping the Heart — have made him among the most widely read Puritans across subsequent centuries.",
'thomas-watson': "Thomas Watson (c. 1620–1686) was a Puritan minister whose Body of Divinity — an exposition of the Westminster Shorter Catechism — remains one of the most accessible and devotionally rich introductions to Reformed theology ever written.",
'george-whitefield': "George Whitefield (1714–1770) was the greatest evangelist of the eighteenth century, a Calvinist preacher of unparalleled power who preached an estimated 18,000 sermons on both sides of the Atlantic and was the central figure of the Great Awakening.",
'herman-bavinck': "Herman Bavinck (1854–1921) was the greatest Dutch Reformed theologian of his generation, whose four-volume Reformed Dogmatics is now widely recognized as one of the greatest works of systematic theology ever written.",
'john-newton': "John Newton (1725–1807) was a former slave-ship captain whose dramatic conversion led to ministry at Olney and London, authorship of 'Amazing Grace,' and a public testimony against the slave trade he had once practiced.",
'samuel-rutherford': "Samuel Rutherford (c. 1600–1661) was a Scottish covenanting minister whose letters, written during exile in Aberdeen, are among the most Christ-saturated spiritual writings in the history of the church.",
'richard-baxter': "Richard Baxter (1615–1691) was the most prolific Puritan practical theologian, whose Reformed Pastor transformed how generations of ministers understood their calling and whose Saints' Everlasting Rest remains a devotional classic.",
'thomas-boston': "Thomas Boston (1676–1732) was a Scottish minister whose Human Nature in Its Fourfold State and role in the Marrow Controversy made him one of the most beloved and theologically significant figures in the history of the Church of Scotland.",
'john-bunyan': "John Bunyan (1628–1688) was a Nonconformist tinker and preacher whose Pilgrim's Progress — written during imprisonment for unauthorized preaching — is, after the Bible, the most published and translated book in the history of Christianity.",
}

BIOS_LONG = {
'john-fox': """John Foxe (1516–1587) was an English historian, Protestant martyrologist, and author of one of the most consequential books in English religious history. Born in Boston, Lincolnshire, he studied at Brasenose College and Magdalen College, Oxford, becoming a fellow at Magdalen — but resigned his fellowship rather than comply with the college's Catholic statutes under the reign of Mary I.

When Mary Tudor came to the throne in 1553 and began burning Protestants, Foxe fled to the European continent, joining the community of Protestant exiles in Frankfurt, Strasbourg, and Basel. It was during this exile that he began the enormous work of collecting testimonies, official records, letters, and eyewitness accounts of Protestant martyrs stretching back to John Wycliffe and Jan Hus.

His Acts and Monuments — universally known as Foxe's Book of Martyrs — was first published in Latin in 1554 and in a greatly expanded English edition in 1563. The book ran to thousands of pages and documented in vivid detail the suffering of those burned for their Protestant faith, particularly under Mary I. Among its most memorable passages is the account of Thomas Haukes, who was burned at the stake in 1555 and reportedly raised his charred hands above his head in a pre-arranged signal to watching friends that the grace of God sustained him even in the flames.

The Book of Martyrs became, after the Bible, the most widely read book in Elizabethan England, placed by royal injunction in churches and cathedrals alongside the Scriptures. It shaped English Protestant identity for generations, cementing a deep suspicion of Roman Catholicism and a sense that English Protestants were the heirs of a suffering, faithful church. Foxe himself was a man of remarkable charity for his era — he repeatedly interceded for condemned men on all sides and opposed the burning of Anabaptists.""",

'loraine-boettner': """Loraine Boettner (1901–1990) was born on a farm in Linden, Missouri, and spent his formative years far from the centers of academic theology — yet he became one of the most widely read Reformed authors of the twentieth century. He studied at Princeton Theological Seminary during the final years of the old Princeton orthodoxy, receiving his Th.B. in 1928 and his Th.M. in 1929 under scholars who stood in the tradition of Charles Hodge and B. B. Warfield.

His magnum opus, The Reformed Doctrine of Predestination (1932), was written not as an academic treatise but as a thorough, accessible defense of the five points of Calvinism for ordinary pastors and laypeople. The book marshals Scripture, the Westminster Confession, and the writings of the Reformed tradition into a sustained argument for the sovereignty of God in salvation, and remains one of the most comprehensive popular treatments of the subject ever written in English.

Beyond predestination, Boettner wrote extensively on Roman Catholicism, on the millennium (arguing for postmillennialism), on immortality, and on the inspiration of Scripture. His work Roman Catholicism (1962) became a standard Reformed reference on the subject for decades. Though some of his scholarship has been superseded, his clarity, accessibility, and breadth of coverage secured his lasting place in the Reformed canon.""",

'arthur-w-pink': """Arthur Walkington Pink (1886–1952) was born in Nottingham, England, and after a brief flirtation with Theosophy in his youth, was soundly converted and became one of the most industrious and uncompromising Reformed writers of the twentieth century. He was largely self-taught theologically, never having attended seminary, yet produced a body of work that has shaped Reformed thought across denominational lines.

Pink spent much of his life as an itinerant preacher and writer — living at various times in the United States, Australia, and finally the Scottish island of Lewis — while producing the monthly Studies in the Scriptures, which he wrote, edited, and published almost entirely himself from 1922 until 1953. At the height of its circulation it reached only a few hundred subscribers, and Pink died largely unknown. In the decades after his death, however, the Banner of Truth Trust republished his works and he was discovered by a new generation of Reformed readers.

His most enduring works — The Sovereignty of God, The Attributes of God, The Atonement, and his massive Exposition of the Gospel of John — are marked by an unsparing commitment to doctrinal precision, a rich command of Scripture, and a deep concern for personal holiness. Pink's style is direct, his standards uncompromising, and his Christ-centeredness unmistakable. He wrote as a man who believed every word of Scripture and expected his readers to live accordingly.""",

'jonathan-edwards': """Jonathan Edwards (1703–1758) is widely regarded as the greatest theologian and philosopher America has produced. Born in East Windsor, Connecticut, the son and grandson of Congregationalist ministers, he entered Yale College at the age of thirteen and graduated at the top of his class. After a brief pastorate in New York, he joined his grandfather Solomon Stoddard at Northampton, Massachusetts, and succeeded him as pastor in 1729 — a position he would hold for over twenty years.

In the 1730s and 1740s, Northampton became the epicenter of remarkable spiritual awakening. Edwards's careful, eyewitness account of these events in A Faithful Narrative of the Surprising Work of God (1737) attracted attention on both sides of the Atlantic and helped prepare the ground for the transatlantic Great Awakening of the early 1740s. His sermon "Sinners in the Hands of an Angry God" (1741) is the most famous sermon in American history, though it represents only one dimension of a preaching ministry far richer and more varied than that single text suggests.

Dismissed from his Northampton pulpit in 1750 over a controversy about qualifications for communion, Edwards spent the final years of his active ministry as a missionary to Native Americans in Stockbridge, Massachusetts. It was there, paradoxically, that he produced some of his greatest theological works: Freedom of the Will (1754), The Great Christian Doctrine of Original Sin (1758), and the posthumously published The Nature of True Virtue and Concerning the End for Which God Created the World. He was appointed president of Princeton (then the College of New Jersey) in 1758, died weeks later from a smallpox inoculation, and left behind a theological legacy that has shaped Reformed and evangelical thought across the world for nearly three centuries.""",

'benjamin-b-warfield': """Benjamin Breckinridge Warfield (1851–1921) was the last and perhaps the most formidable of the great Princeton theologians, serving as Charles Hodge Professor of Didactic and Polemic Theology at Princeton Theological Seminary from 1887 until his death in 1921 — thirty-four years during which he became the most respected conservative Reformed scholar in the English-speaking world.

Born into a prominent Kentucky family and educated at Princeton College and then Princeton Seminary, Warfield combined extraordinary intellectual gifts with prodigious industry. He read widely in ancient and modern languages, engaged the most demanding critical scholarship of his day, and produced a collected works spanning ten volumes that covers Christology, soteriology, the inspiration and authority of Scripture, Reformed theology, and the history of doctrine.

His most lasting contribution is probably his rigorous defense of the plenary verbal inspiration and inerrancy of Scripture — most fully articulated in The Inspiration and Authority of the Bible — which set the terms for evangelical and Reformed discussion of the subject throughout the twentieth century. His studies of perfectionism, Calvinism, and the person of Christ display the same combination of historical learning, theological precision, and polemical force. Warfield was also, unexpectedly, an early and thoughtful Protestant who took evolution seriously as a scientific question while maintaining full confidence in Scripture — a combination that made him impossible to pigeonhole. He rarely left Princeton after his wife became an invalid in 1876, but his influence was global.""",

'john-owen': """John Owen (1616–1683) is without question the greatest English Puritan theologian, and many would rank him among the most important theological minds in the history of Reformed Christianity. Born in Stadhampton, Oxfordshire, the son of a Puritan minister, he was educated at Queen's College, Oxford, and spent the first years of his ministry struggling with assurance of salvation — an experience that gave his subsequent theology an unusually deep and pastoral character.

His conversion to firm Calvinist convictions, his rise to prominence as a preacher, his friendship with Oliver Cromwell, and his appointment as Vice-Chancellor of Oxford all came in quick succession in the 1640s and 1650s. As Cromwell's chaplain, Owen preached to Parliament on the day after the execution of Charles I. As Vice-Chancellor, he presided over a university that briefly became the most tolerant institution of higher learning in England. With the Restoration in 1660, he lost all his positions and spent the rest of his life as a Nonconformist minister in London, ejected, occasionally harassed, but never silenced.

The range and depth of Owen's works is staggering. His seven-volume commentary on Hebrews is the most thorough ever written. His treatise On the Mortification of Sin in Believers has guided Christians in the fight against sin for three and a half centuries. Communion with God, The Glory of Christ, and Of the Holy Spirit together constitute the most comprehensive Puritan treatment of Trinitarian devotion and theology. His Salus Electorum, Sanguis Jesu — known as The Death of Death in the Death of Christ — remains the definitive Reformed defense of particular atonement. Owen wrote slowly, densely, and with enormous theological precision; C. H. Spurgeon said that if you could understand Owen, you could understand anything.""",

'john-calvin': """John Calvin (1509–1564) was the foremost second-generation Reformer and the theologian whose systematic mind gave the Reformed tradition its characteristic shape. Born in Noyon, France, he was trained as a humanist scholar and lawyer before a sudden conversion — described by him as God "subduing his heart to teachableness" — redirected his life entirely to the cause of evangelical reform.

His Institutes of the Christian Religion, first published in 1536 when Calvin was twenty-six and expanded through four major editions until the definitive 1559 version, is the masterpiece of Reformation theology: clear, comprehensive, deeply biblical, and organized with a lawyer's precision. From the knowledge of God to the final resurrection, it covers the entire range of Christian doctrine in a way that has shaped Protestant theology across every tradition and every century since.

Calvin settled in Geneva in 1536, was expelled in 1538, and returned in 1541 at the city's request — staying until his death in 1564. As the city's leading pastor and teacher, he preached expository sermons through virtually every book of the Bible (often daily), wrote commentaries on almost the entire Bible, corresponded with Protestant rulers and reformers across Europe, founded the Geneva Academy in 1559, and trained the ministers who carried Reformed doctrine into France, Scotland, the Netherlands, England, and beyond. He was driven by a single passion: that God should be glorified in all things, and that the church should be ordered according to Scripture alone.""",

'charles-h-spurgeon': """Charles Haddon Spurgeon (1834–1892) was the most celebrated preacher in the Victorian world, and arguably the most gifted popular preacher in the history of the English-speaking church. Born in Kelvedon, Essex, into a family of Congregationalist ministers, he was converted at fifteen in a Primitive Methodist chapel during a snowstorm when a lay preacher expounded Isaiah 45:22: "Look unto me, and be ye saved, all the ends of the earth."

By the time he was twenty, Spurgeon was drawing crowds of thousands to the New Park Street Chapel in London. By the time he was twenty-three, he was preaching to 10,000 people at a time in the Surrey Gardens Music Hall. The Metropolitan Tabernacle, built to hold his congregation, seated 6,000 and was filled twice every Sunday for over thirty years. He preached on average ten times a week, and his collected sermons fill sixty-three volumes — the largest corpus of books by any individual author in the history of Christianity.

Spurgeon was a thoroughgoing Calvinist, unapologetic about election, particular redemption, and the sovereignty of God in salvation — convictions he believed were simply the doctrines of grace taught in Scripture and summarized in the great confessions of the Reformation. Yet he was also a passionate evangelist who pleaded urgently with sinners to trust Christ. He founded Spurgeon's College to train ministers, ran an orphanage, and supported dozens of charitable works. Near the end of his life he fought the "Downgrade Controversy," warning that evangelical churches were abandoning the authority of Scripture and the doctrines of the Reformation — a battle he largely lost in his lifetime but that history has judged he was right to fight.""",

'j-gresham-machen': """John Gresham Machen (1881–1937) was the most intellectually formidable defender of confessional Presbyterianism in the twentieth century, and the man who drew the sharpest line between genuine Christianity and the theological liberalism that had taken over the mainline Protestant denominations by the 1920s.

Born into a cultured Baltimore family, Machen studied at Johns Hopkins, Princeton Seminary, and in Germany under some of the leading liberal scholars of the day — an experience that clarified rather than shook his convictions. He joined the New Testament faculty at Princeton Seminary in 1906, where he became one of its most admired teachers and produced, in The Origin of Paul's Religion (1921) and The Virgin Birth of Christ (1930), two of the most rigorous works of conservative New Testament scholarship of the era.

His Christianity and Liberalism (1923) is his most important book — a precise, relentless argument that the theological liberalism dominant in Protestant churches was not a form of Christianity at all, but an entirely different religion that had appropriated Christian language while abandoning Christian substance. The book made him famous and deeply controversial. When the northern Presbyterian Church refused to discipline missionaries who denied core doctrines, Machen founded the Independent Board for Presbyterian Foreign Missions in 1933, was suspended from the ministry by the Presbyterian Church USA in 1936, and went on to found what became the Orthodox Presbyterian Church and Westminster Theological Seminary — institutions he believed would preserve the Reformed faith the mainline had surrendered.""",

'john-murray': """John Murray (1898–1975) was a Scottish-born theologian who became, through nearly four decades of teaching at Westminster Theological Seminary, one of the most precise and careful Reformed systematic theologians of the twentieth century. Born on a croft in Sutherland in the Scottish Highlands, he was educated at the Free Church College in Glasgow and then at Princeton Seminary, where he came under the influence of B. B. Warfield and Geerhardus Vos.

He joined the founding faculty of Westminster Theological Seminary in Philadelphia in 1930 and remained there until his retirement to Scotland in 1966 — thirty-six years during which he shaped the theological formation of hundreds of Reformed ministers across North America and beyond. His seminars were legendarily demanding; students said he rarely smiled, but that every sentence he spoke was worth writing down.

His commentary on Romans, published in two volumes in 1959 and 1965, is universally acknowledged as a masterpiece of careful, rigorous exegesis in the Reformed tradition — precise, thorough, and deeply reverent. Redemption Accomplished and Applied (1955) is perhaps the clearest and most economical account of the Reformed doctrine of salvation ever written, tracing the work of Christ from the cross through its application in the life of the believer. His collected writings on topics from covenant theology to systematic theology to ethics fill four volumes and reward the most careful reader. Murray was a man of few words and immense depth.""",

'charles-hodge': """Charles Hodge (1797–1878) was the dominant figure in American Reformed theology for over half a century, teaching at Princeton Theological Seminary from 1820 until his death — fifty-eight years during which he taught an estimated three thousand students and shaped the theological character of American Presbyterianism more than any other individual.

Born in Philadelphia and educated at Princeton College and Princeton Seminary, Hodge spent two years studying in Germany in the early 1820s, engaging the rising tide of German critical theology and coming away confirmed in his Calvinist orthodoxy but with a broader understanding of the theological landscape. On his return he threw himself into teaching, writing, and editing the Biblical Repertory and Princeton Review, which under his direction became the most important Reformed theological journal in America.

His three-volume Systematic Theology (1872–73), published when he was in his seventies, is a monument of comprehensive theological learning — covering every major locus of Christian doctrine from a rigorously Reformed and confessionally Presbyterian perspective. His commentaries on Romans, Ephesians, and the Corinthian letters remain valuable for their careful exegesis and clear doctrinal application. Hodge was also a committed churchman who played a central role in the controversies over slavery, the nature of the church, and the relation of faith and science that convulsed American Presbyterianism in his era. His famous boast that "no new idea" had ever originated at Princeton Seminary — meaning Princeton had held firm to the faith once delivered — was both a point of pride and a target for critics.""",

'archibald-alexander': """Archibald Alexander (1772–1851) was the founding father of Princeton Theological Seminary and one of the most influential figures in the history of American Presbyterianism. Born in Rockbridge County, Virginia, he was educated by private tutors and in 1791 became a licensed preacher for the Hanover Presbytery at the age of seventeen — already showing the combination of evangelical warmth and doctrinal seriousness that would mark his ministry.

He served as a circuit-riding preacher in the Virginia backcountry, as president of Hampden-Sydney College, and as pastor of Third Presbyterian Church in Philadelphia before being appointed in 1812 as the first professor of the newly founded Princeton Theological Seminary. The seminary was established to provide a more rigorous theological education than the colleges could offer, and Alexander shaped its character from the beginning: deeply Calvinistic in doctrine, warmly evangelical in piety, and committed to the Westminster standards as the faithful summary of biblical teaching.

For nearly four decades, Alexander taught at Princeton alongside his son James Waddel Alexander and later Charles Hodge, forming what became known as "the Princeton Theology" — a tradition of careful, confessional Calvinist scholarship that dominated American Presbyterian thought through the nineteenth century. His Thoughts on Religious Experience (1841) and Evidences of the Authenticity, Inspiration, and Canonical Authority of the Holy Scriptures remain valuable examples of his combination of doctrinal precision and pastoral concern.""",

'r-l-dabney': """Robert Lewis Dabney (1820–1898) was the most rigorous systematic theologian the Southern Presbyterian tradition produced, and a figure of genuine intellectual stature whose theological legacy far outlasted the political controversies that surrounded his life. Born in Louisa County, Virginia, he studied at Hampden-Sydney College and Union Theological Seminary in Virginia before embarking on a pastoral ministry that was interrupted by the Civil War.

During the war, Dabney served as chief of staff and adjutant general to Stonewall Jackson — a personal friend — and wrote a biography of Jackson after the general's death that remains a standard source. After the war, he returned to Union Theological Seminary, where he taught systematic theology until 1883, then moved to the newly founded University of Texas, where he taught philosophy until advancing blindness ended his academic career.

His Systematic Theology (originally published as Lectures in Systematic Theology) is the most thorough and rigorous work of systematic theology produced within the Southern Presbyterian tradition — deeply Reformed, closely argued, and drawing on a vast range of theological sources. His five-volume Discussions cover every major area of theology, ecclesiology, philosophy, and social questions. Dabney was also deeply controversial — his defenses of the Confederacy, his opposition to the reunion of Northern and Southern Presbyterians, and his views on race have rightly been criticized. But even those who reject his social views have recognized the power and precision of his theological mind.""",

'j-c-ryle': """John Charles Ryle (1816–1900) was the first Bishop of Liverpool and one of the most effective communicators of Reformed evangelical truth in the Victorian church. Born into a wealthy Cheshire banking family, he was educated at Eton and Christ Church, Oxford, where he was a celebrated athlete and scholar. His family's financial ruin in 1841 and a serious illness around the same time precipitated his conversion to earnest Christian faith.

He spent over three decades as a rural rector — at Helmingham in Suffolk and then at Stradbroke — writing constantly during those years of relative obscurity. His Expository Thoughts on the Gospels (seven volumes) grew out of his parish ministry and became one of the most widely used devotional commentaries in the evangelical world. His Holiness (1877) is a masterpiece of Reformed practical theology, insisting on the absolute necessity of sanctification while grounding it firmly in justification by faith alone. Knots Untied, Old Paths, and Practical Religion cover the full range of Christian doctrine and experience in the same clear, direct, energetic style.

When Disraeli appointed him the first Bishop of Liverpool in 1880, Ryle was sixty-four years old and virtually unknown outside evangelical circles. He proved to be an energetic and effective diocesan bishop, building churches, training clergy, and maintaining the evangelical character of his diocese against both Anglo-Catholic and liberal pressure. His prose style — plain, forceful, and free from theological jargon — made him one of the most accessible Reformed writers of any era.""",

'john-flavel': """John Flavel (c. 1628–1691) was an English Puritan minister whose devotional writings have made him, after Bunyan and Baxter, probably the most widely read of all the Puritans among later generations of evangelical readers. Born the son of a Puritan minister who died of plague in Newgate Prison for his nonconformity, Flavel was educated at University College, Oxford, and ordained to the ministry in 1650.

He served as minister at Dartmouth, Devon, from 1656, developing a ministry to the seafaring community of that port town that gave his writing its characteristic concreteness and practical application — few Puritan writers matched his ability to take a spiritual truth and illustrate it from the experience of storms, voyages, and harbor lights. Ejected from his living in 1662 by the Act of Uniformity, he continued to preach clandestinely to his congregation, sometimes meeting at sea to escape pursuivants.

His most enduring works include The Mystery of Providence (1678) — a meditation on God's governance of every circumstance of the believer's life that has comforted Christians across three centuries — Keeping the Heart (1668), on the maintenance of inward spiritual watchfulness, and Touchstone of Sincerity. His complete works in six volumes cover navigation as a metaphor for the Christian life, the method of grace in the application of redemption, and the full range of Puritan practical divinity. Spurgeon said Flavel's works were "most precious" and that he read him with constant profit.""",

'thomas-watson': """Thomas Watson (c. 1620–1686) was a Puritan minister whose gift for vivid, memorable, and theologically precise writing made him one of the most beloved and most quoted of all the Puritans. Educated at Emmanuel College, Cambridge — the great nursery of Puritan ministers — he served as minister of St. Stephen Walbrook in London from 1646, where he developed a reputation as one of the finest preachers in the city.

Watson was ejected from his living in 1662 along with two thousand other Nonconformist ministers under the Act of Uniformity. He continued preaching where he could, was briefly imprisoned, and after the Declaration of Indulgence in 1672 gathered a congregation that eventually worshipped with Stephen Charnock at Crosby Hall, London. He retired to Barnston in Essex around 1686 and died there.

His Body of Divinity — an exposition of the Westminster Shorter Catechism in the form of sermons — remains one of the most accessible and devotionally rich introductions to Reformed theology ever written. Watson's genius was for concrete illustration: abstract doctrines became vivid and memorable in his hands, and he had an unmatched ability to apply doctrine directly to the conscience and the will. A Divine Cordial (on Romans 8:28), The Doctrine of Repentance, The Beatitudes, and The Lord's Prayer complete a body of work that rewards re-reading across a lifetime. Spurgeon recommended Watson above almost all other Puritan authors for his combination of clarity, depth, and warmth.""",

'george-whitefield': """George Whitefield (1714–1770) was the greatest evangelist of the eighteenth century and one of the most extraordinary preachers in the history of Christianity. Born in Gloucester, the son of an innkeeper, he worked his way through Pembroke College, Oxford, as a servitor — a student who paid his fees by waiting on wealthier students. At Oxford he encountered the Holy Club of John and Charles Wesley, was converted through a long spiritual struggle, and emerged from it with a settled assurance of salvation and a zeal for preaching that he would sustain for the rest of his life.

He was ordained in 1736 and immediately discovered what would become clear over forty years of ministry: that he possessed a natural gift for preaching that was, in the judgment of contemporaries from Benjamin Franklin to David Garrick, utterly unparalleled. His voice carried to tens of thousands in the open air; his dramatic delivery, his mastery of Scripture, and his passionate appeals moved audiences to weeping and conviction wherever he preached. He crossed the Atlantic thirteen times and preached an estimated 18,000 sermons — often multiple times a day.

Whitefield and John Wesley parted in the early 1740s over Whitefield's Calvinism: he could not follow Wesley into Arminianism, and the two conducted a pamphlet controversy that, to their mutual credit, never broke their personal friendship. Whitefield's Calvinism was warm, earnest, and entirely compatible with the most urgent evangelistic appeal — he believed in election precisely because he trusted that God would honor his preaching with conversions. He died in Newburyport, Massachusetts, and was buried beneath the pulpit of Old South Presbyterian Church.""",

'herman-bavinck': """Herman Bavinck (1854–1921) was the greatest Dutch Reformed theologian of his generation and one of the most important systematic theologians in the history of Reformed Christianity. Born in Hoogeveen in the Netherlands, the son of a minister in the Secession Church, he studied at the Theological School in Kampen and then — unusually for a man of his background — at the liberal University of Leiden, where he received his doctorate in 1880. His decision to engage the best critical scholarship of his day rather than retreat from it shaped the character of his theology.

He taught systematic theology at the Theological School in Kampen from 1883 to 1902, then moved to the Free University of Amsterdam founded by Abraham Kuyper, where he taught until his death. The relationship between Bavinck and Kuyper was the defining intellectual partnership of Dutch Reformed thought at the turn of the century: Kuyper the activist and organizer, Bavinck the theologian and synthesizer.

His four-volume Reformed Dogmatics — published between 1895 and 1901 in Dutch and translated into English only in the 2000s — is now widely recognized as one of the greatest works of systematic theology ever written. It is distinguished by its engagement with the entire history of Christian thought, its careful dialogue with modern philosophy and science, its commitment to Scripture and the Reformed confessions, and its overarching vision that "grace restores nature" — that redemption does not destroy creation but fulfills it. Bavinck wrote on psychology, pedagogy, and ethics as well, and brought a synthetic, irenic, and deeply catholic Reformed mind to every subject he touched.""",

'john-newton': """John Newton (1725–1807) led one of the most dramatic lives in the history of the Christian church. Born in London, the son of a sea captain, he lost his mother at the age of seven, went to sea at eleven, and by his twenties had become the captain of a slave ship — a life he later described with horror and without self-exculpation. His conversion came gradually through a terrifying storm at sea in 1748, after which he began to read the Bible and pray, though he continued in the slave trade for several more years.

After leaving the sea, Newton studied under the evangelical minister George Whitefield, was ordained in the Church of England in 1764, and was appointed curate of Olney in Buckinghamshire — a position he held for sixteen years. At Olney he befriended the poet William Cowper, and together they produced the Olney Hymns (1779), one of the most important hymn collections in English — including Newton's own "Amazing Grace," "How Sweet the Name of Jesus Sounds," and "Glorious Things of Thee Are Spoken," and Cowper's "God Moves in a Mysterious Way."

In 1780 he became rector of St. Mary Woolnoth in the City of London, where he ministered for the rest of his life, becoming one of the most widely sought-after spiritual counselors in England. His Cardiphonia (Letters to Spiritual Inquirers) is one of the richest collections of spiritual correspondence in the English language. Near the end of his life, he made a public testimony before Parliament of his former involvement in the slave trade, supporting the abolition movement led by his friend William Wilberforce. He reportedly said, when asked whether his memory had failed enough that he should retire from preaching: "My memory is nearly gone; but I remember two things: that I am a great sinner, and that Christ is a great Savior." """,

'samuel-rutherford': """Samuel Rutherford (c. 1600–1661) was one of the most remarkable figures in the history of Scottish Christianity — a theologian, controversialist, covenanting statesman, and above all a pastor whose letters reveal one of the most ardent and Christ-saturated spirits in the history of the church.

Born in Nisbet in the Scottish borders and educated at the University of Edinburgh, he was appointed professor of humanity there in 1623 but was removed over a moral scandal shortly afterward. He was appointed minister of Anwoth in Galloway in 1627, and it was there that he developed the pastoral ministry — and the suffering — that would mark the rest of his life. His wife died young, his children died young, and in 1636 he was banished from his parish by the Court of High Commission for preaching against Arminianism and Episcopacy, and confined to Aberdeen.

It was during this confinement that he wrote most of the 365 letters that form his enduring monument. Addressed to members of his Anwoth congregation, to noblewomen and lairds, to struggling saints and doubting souls across Scotland, they overflow with what his contemporaries recognized as an almost unearthly love for Christ: "Oh, if ye saw the beauty of Christ!" they cry, again and again. The Letters have been a treasured resource for generations of Christians who found in them a reflection of their own longing and a warming of their own cold hearts.

Rutherford was also a formidable controversialist. His Lex Rex (The Law and the Prince, 1644), written during his time as a member of the Westminster Assembly, argued from Scripture and natural law that rulers are accountable to the law and that tyranny may be resisted — a dangerously radical claim for its day that was publicly burned at the Restoration. He died before he could be tried for treason. His last recorded words were: "I shall shine; I shall see Him as He is; I shall see Him reign, and all His fair company with Him." """,

'richard-baxter': """Richard Baxter (1615–1691) was the most prolific and probably the most influential Puritan practical theologian, a man of tireless energy and passionate pastoral concern who produced, in The Reformed Pastor, one of the most challenging and enduring guides to Christian ministry ever written.

Born in Rowton, Shropshire, and largely self-educated, Baxter was ordained in 1638 and after serving briefly at Bridgnorth was appointed lecturer at Kidderminster in 1641. He transformed that unpromising market town into a model parish through a ministry of intensive personal catechizing and pastoral visiting — going house to house with his assistant each week to teach every family in the parish. The results were extraordinary: Kidderminster became one of the most thoroughly evangelized parishes in England, and Baxter documented his method in The Reformed Pastor (1656), which remains required reading in ministerial training to this day.

His theology was genuinely idiosyncratic — he was a Calvinist in his doctrines of election and grace but modified the doctrine of the atonement in ways that satisfied neither strict Calvinists nor Arminians, and he called himself a "meer Christian" rather than claiming any party label. His irenic instincts and his deep commitment to the visible unity of the church made him an indefatigable but ultimately unsuccessful peacemaker in the denominational conflicts of his era.

After the Restoration he was ejected from Kidderminster, imprisoned twice, and spent his remaining years in London writing and ministering informally. His Saints' Everlasting Rest (1650) — written when he expected to die young — and A Call to the Unconverted remain devotional and evangelistic classics. In total he published around 140 books, and his complete works fill twenty-three volumes.""",

'thomas-boston': """Thomas Boston (1676–1732) was a Scottish minister whose theological clarity, pastoral tenderness, and remarkable inner life made him one of the most beloved figures in the history of the Church of Scotland. Born in Duns in Berwickshire, the son of a covenanting tradesman, he was educated at the University of Edinburgh and ordained in 1699.

He served as minister of Simprin — an obscure parish of about ninety families — from 1699 to 1707, then at Ettrick in the remote borderlands of Selkirkshire from 1707 until his death. Ettrick was poor, isolated, and initially resistant to his ministry, but Boston poured himself into it with extraordinary faithfulness, developing through decades of pastoral experience and theological reflection the works that would outlast his obscurity.

Human Nature in Its Fourfold State (1720), Boston's most famous work, traces the condition of humanity as originally created, as fallen, as regenerate, and as glorified — a schema drawn from a Puritan framework and applied with great pastoral warmth and insight. It became one of the most widely read works in Scotland and went through scores of editions over the next two centuries.

Boston is also remembered for his role in the "Marrow Controversy" of the 1720s, which divided the Church of Scotland. He discovered a copy of The Marrow of Modern Divinity — a seventeenth-century English compilation of Reformed teaching on free grace — in a parishioner's cottage, and his enthusiastic promotion of it led to a prolonged controversy about the relationship between law and gospel, free offer and election. Boston and the "Marrow Men" defended the free and sincere offer of Christ to all, against what they saw as a hyper-Calvinist restriction of the gospel. His Memoirs, published posthumously, offer an extraordinarily transparent account of the inner spiritual life of a man who wrestled deeply with God.""",

'john-bunyan': """John Bunyan (1628–1688) was a tinker's son from Elstow in Bedfordshire whose imprisonment became the occasion for the most widely read work of Christian literature in the English language. Born into poverty and largely uneducated, Bunyan served in the Parliamentary army during the Civil War and in the late 1640s underwent a spiritual crisis of extraordinary intensity — years of doubt, terror, and eventual assurance — that he would later describe in his spiritual autobiography, Grace Abounding to the Chief of Sinners (1666).

He became a Nonconformist preacher associated with the Bedford Meeting, a Baptist congregation, and was arrested in 1660 for preaching without a license. He spent twelve years in Bedford Jail — refusing liberty when it was offered on condition of stopping his preaching — and during that time wrote Grace Abounding and began The Pilgrim's Progress. Released under the Declaration of Indulgence in 1672, he was imprisoned again briefly in 1676, during which time he is thought to have completed The Pilgrim's Progress, published in 1678.

The Pilgrim's Progress is, after the Bible, the most published and translated book in the history of Christianity, having been translated into over 200 languages. The allegory of Christian's journey from the City of Destruction to the Celestial City captures the entire evangelical experience — conviction of sin, conversion, temptation, backsliding, fellowship, suffering, and triumph — with a vividness and psychological accuracy that has made it immediately recognizable to readers across every culture and century. Bunyan also wrote The Holy War, The Life and Death of Mr. Badman, and dozens of other tracts and treatises, all in the same accessible, concrete, vivid prose shaped by the English Bible and his own spiritual experience.""",
}

def run():
    conn = psycopg2.connect(**DB)
    conn.autocommit = False
    cur = conn.cursor()

    # Add bio_long column if it doesn't exist
    cur.execute("""
        ALTER TABLE authors
        ADD COLUMN IF NOT EXISTS bio_long text;
    """)
    print("✓ bio_long column ready")

    updated = 0
    not_found = 0

    slugs = set(BIOS_SHORT.keys()) | set(BIOS_LONG.keys())
    for slug in sorted(slugs):
        short = BIOS_SHORT.get(slug, '').strip()
        long_ = BIOS_LONG.get(slug, '').strip()
        cur.execute(
            "UPDATE authors SET bio = %s, bio_long = %s WHERE slug = %s",
            (short or None, long_ or None, slug)
        )
        if cur.rowcount > 0:
            updated += 1
            print(f"  ✓ {slug}")
        else:
            not_found += 1
            print(f"  ! NOT FOUND: {slug}")

    conn.commit()
    cur.close()
    conn.close()
    print(f"\n✓ Done. Updated {updated} (not found: {not_found}).")

if __name__ == '__main__':
    run()
